# Generated by Django 5.0.3 on 2024-03-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Сладер',
                'verbose_name_plural': 'Сладер',
            },
        ),
        migrations.CreateModel(
            name='MediaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img/')),
                ('slider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_slider', to='slider.slider')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фоты',
            },
        ),
    ]
