# Generated by Django 5.0.3 on 2024-03-12 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaimage',
            options={'verbose_name': 'Фото', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Сладер', 'verbose_name_plural': 'Сладеры'},
        ),
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
